kind: Deployment
apiVersion: apps/v1
metadata:
  name: quotesweb
  labels:
    app: quotesweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotesweb
  template:
    metadata:
      labels:
        app: quotesweb
    spec:
      containers:
        - name: quotes
          image: image-registry.openshift-image-registry.svc:5000/yuchstj824-dev/quotesweb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
